name: rome
description: HTTP package scheduler for Dart
version: 0.0.1
authors:
  - Eus Dima <eusdima@gmail.com>
  - Zino Hofmann <zino@zinoapp.com>
homepage: https://github.com/eusdima/rome

dependencies:
  http: ^0.12.0

# dev_dependencies:

environment:
  sdk: '>=2.1.0 <3.0.0'
